---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ymigotca@gmail.com # add your email 
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: ymigotca@gmail.com # add your email to your cloudflare account
            apiTokenSecretRef:
              name: duck-token-secret
              key: duck-token
        selector:
          dnsZones:
            - "pmoxk.duckdns.org" # change to your zone on CloudFlare
