---
apiVersion: v1
kind: Secret
metadata:
  name: duck-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  duck-token: 386a0818-4791-40af-8ccb-8b8bf2fabd58 # MUST be an API token, NOT a Global API key!!! https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
